"""Adding more column to the field

Revision ID: 03831ff539d8
Revises: 9eb36c830fbc
Create Date: 2022-01-21 10:52:17.059079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03831ff539d8'
down_revision = '9eb36c830fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('education', sa.String(length=100), server_default='', nullable=True))
    op.add_column('users', sa.Column('course', sa.String(length=100), server_default='', nullable=True))
    op.add_column('users', sa.Column('aboout_me', sa.Text(), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'aboout_me')
    op.drop_column('users', 'course')
    op.drop_column('users', 'education')
    # ### end Alembic commands ###
