"""Correct about_me name column

Revision ID: 1285d6c17f6a
Revises: 03831ff539d8
Create Date: 2022-01-21 11:57:54.030054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1285d6c17f6a'
down_revision = '03831ff539d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), server_default='', nullable=True))
    op.drop_column('users', 'aboout_me')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('aboout_me', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
