"""Adding profile view count and post cout

Revision ID: 4697f53dcfae
Revises: 82d1924b4560
Create Date: 2022-02-20 09:09:09.438709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4697f53dcfae'
down_revision = '82d1924b4560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_view_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('profile_view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_view_count')
    op.drop_column('posts', 'post_view_count')
    # ### end Alembic commands ###
