"""adding job_title to database

Revision ID: 4b618899b1d7
Revises: 726f1f1039e6
Create Date: 2022-01-16 21:34:01.187614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b618899b1d7'
down_revision = '726f1f1039e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_title', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job_title')
    # ### end Alembic commands ###
