"""adding total view count

Revision ID: 5db397548e21
Revises: 4697f53dcfae
Create Date: 2022-02-20 15:01:30.716496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db397548e21'
down_revision = '4697f53dcfae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_post_view', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_post_view')
    # ### end Alembic commands ###
