"""setting nullable to false in session_token column

Revision ID: 726f1f1039e6
Revises: 4f9a9a63b78d
Create Date: 2022-01-16 21:12:03.373712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726f1f1039e6'
down_revision = '4f9a9a63b78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'session_token',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'session_token',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###
