"""Changing confirm column to confirmed

Revision ID: 9eb36c830fbc
Revises: edb68bd280bf
Create Date: 2022-01-19 13:38:10.789606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb36c830fbc'
down_revision = 'edb68bd280bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('users', 'confirm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirm', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
