"""adding location to user db

Revision ID: a78ec0ee8261
Revises: 18b48550e406
Create Date: 2022-01-26 20:48:54.941292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78ec0ee8261'
down_revision = '18b48550e406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('loaction', sa.String(length=100), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'loaction')
    # ### end Alembic commands ###
