"""Adding avater column

Revision ID: ad706326e577
Revises: a78ec0ee8261
Create Date: 2022-01-27 07:55:24.960624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad706326e577'
down_revision = 'a78ec0ee8261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_avater_hash', sa.String(length=100), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_avater_hash')
    # ### end Alembic commands ###
