"""removing the unique

Revision ID: e5540c2cdf4a
Revises: 0064bff6f43c
Create Date: 2022-01-16 21:04:07.004567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5540c2cdf4a'
down_revision = '0064bff6f43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_session_token_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_session_token_key', 'users', ['session_token'])
    # ### end Alembic commands ###
