"""Adding true and false to server_default for confirm , and active

Revision ID: edb68bd280bf
Revises: bcb949dc1caf
Create Date: 2022-01-19 13:13:08.181516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb68bd280bf'
down_revision = 'bcb949dc1caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirm', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('users', 'confirm')
    # ### end Alembic commands ###
